###
avatar: /images/avatar.jpg
favicon: /images/favicon.png
# 自动生成的摘要长度 建议文章中手动使用 <!--more--> 效果更佳
excerpt_length: 300

# 搜索
search:
  placeholder: 请输入关键字
  path: /search.xml
  use: plugin

# 不蒜子计数
busuanzi:
  site: true
  page: true
  busuanzi_js: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

# 文末结束语
passage_end_tag:
  enabled: true
  text: --- 本文结束 <i class="fa fa-heartbeat"></i> The End ---

# Google Adsense广告代码
google_adsense:
  enabled: true
  footer: ../_adsense/footer.ejs
  sidebar: ../_adsense/sidebar.ejs
  banner: ../_adsense/banner.ejs

# 使用Mathjax渲染数学公式
mathjax:
  enabled: true
  src: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 主题颜色
theme_color:
  primary: blue-grey #teal
  accent: blue

# 菜单
menu:
  home: / || home
  #about: /about/ || user
  tags: /tags/ || bookmark
  categories: /categories/ || folder
  archives: /archives/ || archive
  sitemap: /sitemap.xml || map
  #resources: /resources || download

# 页脚
footer:
  since: 2015
  # If not defined, `author` from Hexo main config will be used.
  powered: true
  theme: true
  beian:
    enable: true
    icp: 
  icon:
    # Icon name in fontawesome, see: https://fontawesome.com/v4.7.0/icons/
    # `heart` is recommended with animation in red (#ff0000).
    enabled: true
    name: fas fa-heart
    color: "#d9333f"

# 页面    
page:
  tag_count: true

# 评论
comment:
  use: gitalk
  ## Gitalk
  gitalk_client_id: 
  gitalk_client_secret: 
  gitalk_repo: 
  gitalk_owner: 
  gitalk_sid_type:
  gitalk_distractionFreeMode: true
  ## Disqus
  disqus_shortname:
  ## Livere
  livere_data_uid:
  ## Valine
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  ## 畅言
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:

# 社交链接
social:
  GitHub: https://github.com/kb1000fx || fab fa-github
  Steam: https://steamcommunity.com/profiles/76561198346798163 || fab fa-steam
  E-Mail: mailto:kb1000fx@gmail.com || fas fa-envelope
  #Weibo: https://weibo.com/yourname || weibo
  #Google: https://plus.google.com/yourname || google
  #Twitter: https://twitter.com/yourname || twitter
  #FB Page: https://www.facebook.com/yourname || facebook
  #VK Group: https://vk.com/yourname || vk
  #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
  #YouTube: https://youtube.com/yourname || youtube
  #Instagram: https://instagram.com/yourname || instagram
  #Skype: skype:yourname?call|chat || skype

site_verification:
  google:
  baidu:
analytics:
  google_site_id:
  baidu_site_id:
  cnzz_site_id:
